version: 2

jobs:
  deploy:
    docker:
      - image: circleci/buildpack-deps:18.04-curl
    steps:
      - checkout
      - run:
          name: Trigger deploy
          command: |
            curl -X GET https://api.vapor.red/v1/apps/$RED_ID/deployments/trigger?token=$RED_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
